### ISSUE TITLE
Problemas com a pasta frontend

### ISSUE THREAD

**Issue by vyamashiro** [jose-renato-m/be-the-hero#1]
Vi seu repositório por curiosidade (também estou fazendo a semana Omnistack) e percebi que você cometeu o mesmo erro que eu, provavelmente você deu um "git init" na pasta frontend (por isso ela aparece um pouco diferente abaixo), com esse erro o git vai ignorar os arquivos dessa pasta.

![Capturar](https://user-images.githubusercontent.com/15017935/78180830-b82aec00-7439-11ea-9dd6-376a712affc6.PNG)

tenta entrar na pasta frontend e excluir o arquivo .git (que está oculto), ou cria uma outra pasta frontend e transfere os arquivos para lá. Abraço.

**Comment by jose-renato-m** [comment]
Olá, @vyamashiro . Então, cara.....semana passada deu isso também. Como eu aprendi a mexer no git via Git Bash......aí eu achava que era por causa disso, aí recomecei do zero e tentei seguir pelo vídeo do Diego.....mas deu a mesma coisa. Como eu faço isso que você me falou? Tem como você me dar uma instruçãozinha aí, cara?

**Comment by vyamashiro** [comment]
Posso sim Jose! Primeiro tenta apaga a pasta .git dentro da pasta frontend.
Olha na figura abaixo, eu fui em exibir e cliquei em "itens ocultos" (Windows 8)
![Capturar](https://user-images.githubusercontent.com/15017935/78201721-b6c4e800-7468-11ea-8acf-c41b867ddbbc.PNG)

Apagando esse arquivo e sobe os arquivos novamente para o github (na pasta que contem os arquivos backend e frontend) o problema deve se resolver.

Caso tenha dificuldades me avise.

**Comment by jose-renato-m** [comment]
Fala, amigo. É o seguinte.......tentei fazer tudo que vc me orientou aqui. Apaguei o arquivo oculto .git de dentro da pasta frontend, aí tentei dar o commit e não aconteceu nada. Criei uma nova pasta frontend e transferi todos os arquivos da antiga pasta frontend para a nova, modifiquei alguns arquivos dei o commit, dei o git push e fica no mesmo. O que eu percebi: quando eu faço alguma alteração em algum arquivo da pasta de backend, o terceiro ícone do lado esquerdo do VSCode, que justamente é o ícone de controle de versão marca que houve uma modificação. Já quando eu faço isso em algum arquivo dentro da pasta frontend e salvo o arquivo, o controlador de versão não marca que houve alteração, como se a pasta frontend não existisse para ele. Não sei o que fazer. Você saberia?

**Comment by vyamashiro** [comment]
Esqueci de falar uma coisa, apaga a pasta "frontend" que está dentro do seu repositório remoto no github antes de enviar novamente, olhei no seu repositório e notei que a pasta continua com o mesmo símbolo de "submodulo".

Só lembrando que antes de fazer o comando git commit fazer o comando git add . para "marcar" todos os arquivos para commit. 

Caso não de certo, envia print de tela por aqui para eu poder ver o que o git está dizendo de erro, tenta usar o comando git status.

**Comment by jose-renato-m** [comment]
Como deleto essa pasta? Não consigo acessá-la aqui no GitHub. A não ser que eu apague esse repositório inteiro e crie novamente ele vazio. Fiz isso da última vez, quando recomecei o projeto. Tem alguma forma de apagar essa pasta meio que "fantasma" aqui do GitHub? Procurei no options aqui e não encontrei.

**Comment by vyamashiro** [comment]
Putz, é verdade, eu também não consegui apagar e acabei apagando o repositório remoto inteiro e reenviando tudo.

Você também pode tentar renomear a pasta do seu repositório local para frontend2 ou algo assim só para testar se o problema se resolve.

**Comment by jose-renato-m** [comment]
Melhor apagar o repositório remoto. Vou apagar, camarada......então esse histórico de issue vai pra casa do chapéu....rsrsrsrs....mas qualquer coisa eu entro em contato com vc no novo repositório, blz?......abraço.

**Comment by jose-renato-m** [comment]
Ah, desculpe.....desde já, obrigado pela ajuda!!!
